name: utility_manager_flutter
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  # awesome_notifications: ^0.7.4+1
  cupertino_icons: ^1.0.2
  # date_time_picker: ^2.1.0
  flutter:
    sdk: flutter
  # flutter_riverpod: ^2.1.1
  flutter_riverpod: ^2.1.1

  # flutter_slidable: ^2.0.0
  flutter_slidable: ^2.0.0
  provider: any

  lottie: ^2.1.0
  share: ^2.0.4
  sliding_up_panel: ^2.0.0+1
  # supabase: ^1.2.0
  # supabase: ^1.2.0

  # supabase_flutter: ^1.2.2
  supabase_flutter: ^1.2.2
  shared_preferences: ^2.0.15
  # webview_flutter: ^4.0.0
  
  # webview_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
